### ISSUE TITLE
ignore feeds older than X number of days fails

### ISSUE THREAD

**Issue by dskrad** [m3nu/upodder#17]
the oldness argument is supposed to allow the script to ignore feed items older than X number of days (default=30). If I try to use this option, it always fails because the number I enter on the commandline is a string instead of an int.

The fix is easy: please add `type=int` to the add_argument() function

The default=30 always works, because 30 is an int. But commandline arguments are interpreted as strings by default.

**Comment by m3nu** [comment]
Good input. Never needed that option. Will change.

**Comment by dskrad** [comment]
Created pull request from a branch that fixes this.

**Comment by m3nu** [comment]
Thanks. The build fails because it won't export my env variables. Rest is fine. Merging.
