### ISSUE TITLE
Updating some feeds fails silently

### ISSUE THREAD

**Issue by dskrad** [m3nu/upodder#19]
For the following feed, it fails to show or download the latest 3 episodes:
https://www.relay.fm/clockwise/feed

There is no error message shown. I have not had a chance to debug this feed. Seems like a valid feed on feedvalidator.com

**Comment by m3nu** [comment]
Thanks for letting me know. The feed also opens in `feedparser`, which we use to open feeds. So maybe a field is missing. Will have a look.

**Comment by dskrad** [comment]
I found the issue...the filetype in this feed is 'audio/mp3' 

the script only looks for 'audio/mpeg'

**Comment by m3nu** [comment]
Ah. That's too strict. We should accept all `audio/*`

**Comment by m3nu** [comment]
Added the new mime-type. There is the `mimetypes` lib in python 2/3 that would handle it better, but since we use the list to find qualified enclosures, I'll leave it as is for now.

Via 795f832 new version 0.6.7
